### ISSUE TITLE
Have this project Xiaomi home devices support?

### ISSUE THREAD

**Issue by LightVolk** [chkr1011/Wirehome.Core#12]
Have this project Xiaomi home devices support?

P.S. I found [this](https://github.com/sigland/mi-home)  project.

**Comment by chkr1011** [comment]
Hi,
at the moment it does not but should be fairly easy be migrated to a Python adapter because as I can see the protocol is based on UDP.

Best regards
Christian

**Comment by LightVolk** [comment]
@chkr1011 , thanks!
